name: Bog-API-Build
on: [push]

jobs:
  build_nuget:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
       
    - name: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
      
    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: build-dotnet
      run: dotnet build --nologo
    
    - name: pack-nuget-packages
      run: dotnet pack -o ./nugetPublish --nologo

    - name: push-nuget-package
      run: dotnet nuget push ./nugetPublish/Bog.Api.Common.1.0.0.nupkg --source ${nuget_source_url} --no-service-endpoint -k ${nuget_mgmt_token} 
      env:
        nuget_mgmt_token: ${{ secrets.nuget_mgmt_token }}
        nuget_source_url: ${{ 'https://nuget.pkg.github.com/pirahawk/index.json' }}  

    - name: print-directory 
      run: ls -la

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:     
    - name: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
      
    - name: checkout-repo
      uses: actions/checkout@v2
      with:
        clean: 'true'

    - name: run-tests
      run: dotnet test --nologo

  print_stuff:
    name: Print Stuff
    runs-on: ubuntu-latest
    steps:     
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"